CREATE TABLE CLIENTE(
    cod_cliente INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR (11)
);

CREATE TABLE LIVRO(
    cod_livro INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(100),
    isbn VARCHAR(20)
)